/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc.h"
#include "gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay()
{
	for(uint32_t i = 0; i<=100000; i++){}
}
int main(void)
{
	GPIO_Handle_t ledGreen, ledOrange, ledRed, ledBlue;

	ledGreen.GPIOx = GPIOD;
	ledGreen.pinConfig.GPIO_mode = GPIO_output;
	ledGreen.pinConfig.GPIO_ospeed = GPIO_high;
	ledGreen.pinConfig.GPIO_otype = GPIO_pushPull;
	ledGreen.pinConfig.GPIO_pinNum = GPIOPin12;
	ledGreen.pinConfig.GPIO_pupdtype = GPIO_noPupd;

	ledOrange.GPIOx = GPIOD;
	ledOrange.pinConfig.GPIO_mode = GPIO_output;
	ledOrange.pinConfig.GPIO_ospeed = GPIO_high;
	ledOrange.pinConfig.GPIO_otype = GPIO_pushPull;
	ledOrange.pinConfig.GPIO_pinNum = GPIOPin13;
	ledOrange.pinConfig.GPIO_pupdtype = GPIO_noPupd;

	ledRed.GPIOx = GPIOD;
	ledRed.pinConfig.GPIO_mode = GPIO_output;
	ledRed.pinConfig.GPIO_ospeed = GPIO_high;
	ledRed.pinConfig.GPIO_otype = GPIO_pushPull;
	ledRed.pinConfig.GPIO_pinNum = GPIOPin14;
	ledRed.pinConfig.GPIO_pupdtype = GPIO_noPupd;

	ledBlue.GPIOx = GPIOD;
	ledBlue.pinConfig.GPIO_mode = GPIO_output;
	ledBlue.pinConfig.GPIO_ospeed = GPIO_high;
	ledBlue.pinConfig.GPIO_otype = GPIO_pushPull;
	ledBlue.pinConfig.GPIO_pinNum = GPIOPin15;
	ledBlue.pinConfig.GPIO_pupdtype = GPIO_noPupd;

	RCC_AHB1_Init(GpioD, ENABLE);

	GPIO_Init(&ledGreen);
	GPIO_Init(&ledOrange);
	GPIO_Init(&ledRed);
	GPIO_Init(&ledBlue);

	GPIO_Led_ON(&ledGreen);
	delay();
	GPIO_Led_ON(&ledOrange);
	delay();
	GPIO_Led_ON(&ledRed);
	delay();
	GPIO_Led_ON(&ledBlue);

	delay();
	GPIO_Led_OFF(&ledGreen);
	delay();
	GPIO_Led_OFF(&ledOrange);
	delay();
	GPIO_Led_OFF(&ledRed);
	delay();
	GPIO_Led_OFF(&ledBlue);

    /* Loop forever */
	/*while(1)
	{
		GPIO_Toggle(&led);
		delay();

	}*/
}
